bookme_admin:
  routes:
    bookme_home:
      path: /
      controller: Bookme\Admin\Controller\HomeController
      method: GET
      action: display
    bookme_home_redirect:
      path: /home
      controller: Bookme\Admin\Controller\HomeController
      method: GET
      action: display
    bookme_admin_login:
      prefix: /login
      controller: Bookme\Admin\Controller\LoginController
      routes:
        bookme_admin_login_get:
          path: /
          method: GET
          action: display
        bookme_admin_login_post:
          path: /
          method: POST
          action: logIn
    bookme_admin_logout:
      path: /logout
      controller: Bookme\Admin\Controller\LoginController
      method: GET
      action: logOut
    bookme_admin_users:
      prefix: /users
      controller: Bookme\Admin\Controller\UserController
      routes:
        bookme_admin_users_list:
          path: /
          method: GET
          action: list
        bookme_admin_users_getOne:
          path: /(\d+)/
          method: GET
          action: getOne
        bookme_admin_users_ban:
          path: /(\d+)/ban
          method: GET
          action: ban
    bookme_admin_books:
      prefix: /books
      controller: Bookme\Admin\Controller\BookController
      routes:
        bookme_admin_books_list:
          path: /
          method: GET
          action: list
        bookme_admin_books_getOne:
          path: /(\d+)/
          method: GET
          action: getOne
    bookme_admin_genres:
      prefix: /genres
      controller: Bookme\Admin\Controller\GenreController
      routes:
        bookme_admin_genres_list:
          path: /
          method: GET
          action: list
    authors:
      prefix: /authors
      controller: Bookme\Admin\Controller\AuthorController
      routes:
        bookme_admin_authors_list:
          path: /
          method: GET
          action: list
    bookme_admin_donations:
      prefix: /donations
      controller: Bookme\Admin\Controller\DonationController
      routes:
        bookme_admin_donations_list:
          path: /
          method: GET
          action: list