services:
  db:
    image: mariadb:10.8
    volumes:
      - "./mysql/conf.d:/etc/mysql/conf.d"
      - "./mysql/data:/var/lib/mysql"
    environment:
      - TZ=Europe/Paris
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  nginx:
    build: ./nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./logs:/var/log"
      - "../:/bookme"
    environment:
      - TZ=Europe/Paris
    ports:
      - "80:80"
      - "443:443"

  php:
    build: ./php
    environment:
      - TZ=Europe/Paris
    volumes:
      - "./php/custom-conf.ini:/usr.local.etc/php-fpm.d/99-custom.ini"
      - "../:/bookme"
