bookme_api:
  routes:
    bookme_users:
      prefix: /users
      controller: Bookme\API\Controller\UserController
      routes:
        bookme_api_users:
          method: GET
          path: /
          action: list
        bookme_api_user_create:
          method: POST
          path: /
          action: create
        bookme_api_user_get:
          method: GET
          path: /(\d+)/
          action: get
        bookme_api_user_delete:
          method: DELETE
          path: /(\d+)/
          action: delete
        bookme_api_user_update:
          method: PATCH
          path: /(\d+)/
          action: update
        bookme_api_user_list_books:
          method: GET
          path: /(\d+)/books
          action: listUsersBooks
        bookme_api_user_password:
          method: GET
          path: /login/
          action: checkLoginInfo
        bookme_api_user_messages:
          prefix: /(\d+)/messages/
          controller: Bookme\API\Controller\MessageController
          routes:
            bookme_api_user_messages_list:
              method: GET
              path: /
              action: list
            bookme_api_user_messages_create:
              method: POST
              path: /
              action: create
            bookme_api_user_messages_recipient:
              method: GET
              path: /(\d+)/
              action: get
    bookme_api_books:
      prefix: /books
      controller: Bookme\API\Controller\BookController
      routes:
        bookme_api_books_list:
          path: /
          method: GET
          action: list
        bookme_api_books_get:
          path: /(\d+)/
          method: GET
          action: get
        bookme_api_books_create:
          path: /
          method: POST
          action: create
        bookme_api_books_update:
          path: /(\d+)/
          method: PATCH
          action: update
        bookme_api_books_delete:
          path: /(\d+)/
          method: DELETE
          action: delete
        bookme_api_books_comment:
          path: /(\d+)/comment/
          method: POST
          action: comment
    bookme_api_authors:
      prefix: /authors
      controller: Bookme\API\Controller\AuthorController
      routes:
        bookme_api_authors_list:
          path: /
          method: GET
          action: list
        bookme_api_authors_get:
          path: /(\d+)/
          method: GET
          action: get
        bookme_api_authors_create:
          path: /
          method: POST
          action: create
        bookme_api_authors_update:
          path: /(\d+)/
          method: PATCH
          action: update
        bookme_api_authors_delete:
          path: /(\d+)/
          method: DELETE
          action: delete
    bookme_api_genres:
      prefix: /genres
      controller: Bookme\API\Controller\GenreController
      routes:
        bookme_api_genres_list:
          path: /
          method: GET
          action: list
        bookme_api_genres_get:
          path: /(\d+)/
          method: GET
          action: get
        bookme_api_genres_create:
          path: /
          method: POST
          action: create
        bookme_api_genres_update:
          path: /(\d+)/
          method: PATCH
          action: update
        bookme_api_genres_delete:
          path: /(\d+)/
          method: DELETE
          action: delete
    bookme_api_cities:
      prefix: /cities
      controller: Bookme\API\Controller\CityController
      routes:
        bookme_api_cities_list:
          path: /
          method: GET
          action: list
        bookme_api_cities_get:
          path: /(\d+)/
          method: GET
          action: get
        bookme_api_cities_create:
          path: /
          method: POST
          action: create
        bookme_api_cities_update:
          path: /(\d+)/
          method: PATCH
          action: update
        bookme_api_cities_delete:
          path: /(\d+)/
          method: DELETE
          action: delete
    bookme_api_zipcodes:
      prefix: /zipcodes
      controller: Bookme\API\Controller\ZipCodeController
      routes:
        bookme_api_zipcodes_list:
          path: /
          method: GET
          action: list
        bookme_api_zipcodes_get:
          path: /(\d+)/
          method: GET
          action: get
        bookme_api_zipcodes_create:
          path: /
          method: POST
          action: create
        bookme_api_zipcodes_delete:
          path: /(\d+)/
          method: DELETE
          action: delete
        bookme_api_zipcodes_link_city:
          path: /(\d+)/link/
          method: POST
          action: linkToCity
        bookme_api_zipcodes_unlink_city:
          path: /(\d+)/unlink/
          method: DELETE
          action: unlinkCity
    